### ISSUE TITLE
`focalLengthControl=indirect` does nothing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics-basics#15]
While reviewing #3 I tested all query parameters with their non-default values, including `focalLengthControl=indirect`, `add2FPointsCheckbox=false`, `addGuidesCheckbox=true`, and `cueingArrowsEnabled=false`. The latter three all behaved as expected. 

However `focalLengthControl=indirect` does nothing in the Basics version. The focal length control is direct - there is a Focal Length NumberControl rather than the IOR/ROC controls. For comparison purposes, I tested the non-default value `focalLengthControl=direct` in the full version and it behaves as expected. 

Steps to reproduce:
1. Open master with `focalLengthControl=indirect`: https://bayes.colorado.edu/dev/phettest/geometric-optics-basics/geometric-optics-basics_en.html?ea&brand=phet&focalLengthControl=indirect
2. Observe the Focal Length NumberControl:  
<img src="https://user-images.githubusercontent.com/8419308/160939997-6049f14d-e8ea-43d0-a497-63c139d1c047.png" width=200>

**Comment by pixelzoom** [comment]
It's currently behaving as was requested. From https://github.com/phetsims/geometric-optics-basics/issues/2#issuecomment-998203690, it was requested to ignore the `focalLengthControl` query parameter in GO:Basics:

> - [x] Ignore ?focalLengthControl, default focalLengthControlTypeProperty to 'direct', no Options dialog

@arouinfar Do you want to change that?

**Comment by pixelzoom** [comment]
Not that you'd be looking at the code. But the current behavior is well-documented. In geometric-optics-basics-main.ts:

```js
// In Geometric Optics: Basis, we want to ignore the focalLengthControl query parameter, and use the 'direct' method
  // of setting focal length.
  GOGlobalOptions.focalLengthModelTypeProperty.value = 'direct';
```

And if you do want to change the behavior, it's relatively easy to make `focalLengthControl` query parameter settable by GO:Basics. 

Also note that the `focalLengthModelControl` PhET-iO element is part of the PhET-iO API (and Studio) tree in both GO and GO:Basics.

**Comment by arouinfar** [comment]
> @arouinfar Do you want to change that?

Yes, let's change that. That decision pre-dated the conversation about the instrumentation of derivative sims. Clients can use `global.view.options.focalLengthModelTypeProperty` to change the focal length model, but it'd be a more consistent experience with Geometric Optics to use the query parameter. Disabling the query parameter seems unnecessary, especially since other query parameters (like Guides) were left funcitonal.

**Comment by pixelzoom** [comment]
On hold until 1.1 prototype is published.  I don't want to introduce master changes that make it more difficult to cherry-pick.

**Comment by pixelzoom** [comment]
The `focalLengthControl` query parameter is now read by GO:Basics.  The associated radio buttons in the Options dialog are still excluded by default, but can be made visible via Studio/iO.

@arouinfar ready for review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master.
