### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics-basics#19]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/799, I am getting the message "Unable to check for Updates" in version 1.2.0-dev.2 and in master. This doesn't happen with the full version of Geometric Optics. 

**Steps to reproduce**
1. Go to the PhET menu and select "Check for Updates"

**Visuals**
Console message:
<img width="518" alt="Screen Shot 2022-04-18 at 12 18 04 PM" src="https://user-images.githubusercontent.com/87318828/163838567-5a28cb6c-a0e3-4d93-a8e3-a3dda52c5c39.png">

<img width="673" alt="Screen Shot 2022-04-18 at 11 57 05 AM" src="https://user-images.githubusercontent.com/87318828/163838086-69ed3675-c3b3-43aa-9adf-e0058cc48d08.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics: Basics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics-basics/1.2.0-dev.2/phet/geometric-optics-basics_all_phet.html
Version: 1.2.0-dev.2 2022-04-15 20:59:03 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Language: en-US
Window: 1403x701
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
PHET > Check for Updates only works (and only makes sense) after a sim has been published to the PHET website.   Geometric Optics has been published, Geometric Optics: Basics has not.   So that describes the behavior here, and it's expected.  Closing.
