### ISSUE TITLE
Requirements for Geometric Optics: Basics

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#2]
In 11/11/21 design meeting, and in https://github.com/phetsims/geometric-optics/issues/253#issuecomment-965554211, we decided to pursue a Basics version of this sim, rather than adding an Intro screen.

**Comment by samreid** [comment]
> On the other end of the spectrum is PhET-iO: it's difficult to change what PhET-iO elements are created, so that things that are not relevant to Basics are never created

We have faced this in Circuit Construction Kit and in Center and Spread.  For instance, in center and spread, this code only instruments the velocity of an object in the soccer screens:

```ts
this.velocityProperty = new Vector2Property( options.velocity, {
  tandem: objectType === CASObjectType.SOCCER_BALL ?
          options.tandem.createTandem( 'velocityProperty' ) :
          Tandem.OPT_OUT
} );
```

To clarify.  The `velocityProperty` is always created, but a PhET-iO element is only created when appropriate.

We have also adjusted tandem names as appropriate for the context:

```ts
this.addLinkedElement( casObject, {
  tandem: options.tandem.createTandem(
    casObject.objectType === CASObjectType.SOCCER_BALL ? 'soccerBall' :
    'dataPoint'
  ),
  phetioState: false
} );
```

**Comment by pixelzoom** [comment]
Yes, I can see how it can be accomplished, and I've done conditional instrumentation in the past.  It's more difficult to implement, more difficult to test fully, and harder to maintain.  So the question is: Does PhET want to incur the cost to do this?

**Comment by pixelzoom** [comment]
This issue is supposed to be about general requirements. So moving comments related to PhET-iO design to #2.

**Comment by pixelzoom** [comment]
Notes to myself...  Here are the things that need to know whether we're running the Basics version, and the path to get there. 

**Concave lens only**:
LensModel > Lens options.opticShapes

**Flat mirror only**:
MirrorModel > Mirror options.opticShapes

**Mirror origin centered on the screen**:
MirrorScreenView > options.getViewOrigin

**Mirror optical object positions**:
MirrorModel options.arrowObject1Position
MirrorModel options.framedObjectPosition

**Checkbox visibility**:
LensScreenView & MirrorScreenView > GOSCreenView > GOControlPanel > VisibilityCheckboxGroup > ‘Second Point’ object literal
MirrorScreenView > GOSCreenView > GOControlPanel > VisibilityCheckboxGroup > ‘Focal Points (F)’ object literal
MirrorScreenView > GOSCreenView > GOControlPanel > VisibilityCheckboxGroup > ‘2F Points’ object literal

**Object/Image labels**:
LensScreenView & MirrorScreenView > GOScreenView > ArrowObjectSceneLabelsNode: objectLabelString
LensScreenView & MirrorScreenView > GOScreenView > FramedObjectSceneLabelsNode > ArrowObjectLabelNode
LensScreenView & MirrorScreenView > GOScreenView > FramedObjectSceneLabelsNode > ArrowImageLabelNode
LensScreenView & MirrorScreenView > GOScreenView > LightObjectSceneLabelsNode > LightObjectLabelNode
LensScreenView & MirrorScreenView > GOScreenView > LightObjectSceneLabelsNode > LightImageLabelNode

**Comment by pixelzoom** [comment]
Regarding this requirement:
> - [ ] Label 'Object' and 'Image', not 'Object 1' and 'Image 1'

I made the Basics version a bit more flexible than this. By default, numbered labels are not used in the Basics version. But if a second object/image is made visible (by setting `secondPointVisibleProperty` to true) then the sim will switch to numbered labels.

**Comment by pixelzoom** [comment]
@arouinfar Geometric Optics: Basics is ready for review. The PhET-iO API (and Studio tree) is identical to Geometric Optics; we'll discuss that in #3.  But I consider it a nice "feature".

**Comment by pixelzoom** [comment]
An additional change we could make in the Mirror screen is to allow free dragging of the framed objects, and add the drag-locked toggle button.  But I'm reluctant to do that until PhET-iO decisions have been made in #3.

**Comment by arouinfar** [comment]
@pixelzoom the sim looks great! I agree that it would be a big improvement to allow free-dragging of the object on the Mirror screen, but it makes sense to defer until #3 is settled.

**Comment by pixelzoom** [comment]
Tracking free-dragging in the Mirror screen in https://github.com/phetsims/geometric-optics-basics/issues/5.

**Comment by pixelzoom** [comment]
@arouinfar This is ready for review.

**Comment by pixelzoom** [comment]
From [implementation-notes.md](https://github.com/phetsims/geometric-optics-basics/blob/master/doc/implementation-notes.md), here's where we ended up with these requirements.

... here's a summary of how _Geometric Optics: Basics_ differs from _Geometric Optics_. Unless specifically noted, these differences can be "undone" via PhET-iO.

_Lens_ screen:
* Convex lens only. Possible to add concave lens via PhET-iO.
* No radio buttons to select the optic shape.
* No second optical object.  Hide the "Second Point" checkbox.
* Label 'Object' and 'Image', not 'Object 1' and 'Image 1', unless a second object is added via PhET-iO.

_Mirror_ screen:
* Flat mirror only. NOT possible to add concave and convex mirror via PhET-iO.
* No radio buttons to select the optic shape.
* Change screen icon to a flat mirror
* Since we have only a flat mirror, move origin to the same screen coordinates as the _Lens_ screen.
* No second optical object.  Hide the "Second Point" checkbox.
* Label 'Object' and 'Image', not 'Object 1' and 'Image 1', unless a second object is added via PhET-iO.
* Remove checkboxes for “Focal Points”, "2F Points" on Mirror screen. Not possible to add them.

Global:
* Default `focalLengthControlTypeProperty` to 'direct', and remove "Focal Length control" from the Options dialog.
* Default `add2FPointsCheckboxProperty` to `true`, so that "2F Points" checkbox is visible on _Lens_ screen.

**Comment by arouinfar** [comment]
Thanks for the summary @pixelzoom. Geometric Optics: Basics looks great!
