### ISSUE TITLE
Console errors while fuzzing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics-basics#20]
For https://github.com/phetsims/qa/issues/799.
While fuzzing the sim on Win 11 Chrome for a memory test these console errors appeared. They did not seem to crash the sim.
<img width="349" alt="fuzzconsolebasics" src="https://user-images.githubusercontent.com/41024075/163885793-c250f630-150c-4a6e-9a3d-b932d9805285.png">

**Comment by pixelzoom** [comment]
This a duplicate of https://github.com/phetsims/geometric-optics-basics/issues/19, but with fuzz testing instead of manually choosing PhET > Check for Updates.
