### ISSUE TITLE
Geometric Optics: Basics - Publish 1.3 with PhET-iO, UI Sound, Alt Input

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#25]
From duplicate https://github.com/phetsims/geometric-optics-basics/issues/18#issue-1188843816:

See notes in https://github.com/phetsims/geometric-optics/issues/387#issuecomment-1085155336.

The first public version of Geometric Optics: Basics will be 1.2.  It will be published at the same time as Geometric Optics 1.2, and its version number will be adjusted to match.

**Comment by pixelzoom** [comment]
This will be the first release of this sim. It has been ready for QA since 3/18/2022 (3.5 months).  It has not progressed because it's coupled to "PhET-iO batch release", which originally had a milestone of 4/1/2022.   Should a brand=phet release of this sim be decoupled from the "PhET-iO batch release"?

**Comment by kathy-phet** [comment]
Create dev test issue and move into QA ~8/17/2022

**Comment by pixelzoom** [comment]
8/17/2022 has come and gone, so I'm assuming that priorities have changed.

Unassigning until this becomes a priority.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics-basics/issues/27, 1.2 will be a brand=phet release.  So this release will be 1.3.  Adjusting the issue title accordingly.

**Comment by pixelzoom** [comment]
... to be done at the same time as:
* https://github.com/phetsims/geometric-optics/issues/278

**Comment by pixelzoom** [comment]
This will be tracked in https://github.com/phetsims/geometric-optics/issues/278.  Closing.
