### ISSUE TITLE
Geometric Optics: Basics - publish 1.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#27]
From 10/27/2022 PhET-iO meeting...

Because https://github.com/phetsims/geometric-optics-basics/issues/25 (Geometric Optics: Basics - Publish 1.2 with PhET-iO, UI Sound, Alt Input) is not going to be completed for awhile, we're going to move ahead with publishing a PhET-brand version. 

I'll review issues, then get this going at the beginning of next week.

**Comment by pixelzoom** [comment]
We have a little version numbering problem to work out first.  To keep the version numbers in sync between GO and GO:Basics, we had bumped GO:B to 1.2.  And 2 dev version have been published for #25.  I'll ruminate on how to address this.

**Comment by pixelzoom** [comment]
Correction... GO is currently at 1.1 on the PhET website. So we'd like GO:B to also be 1.1.

**Comment by pixelzoom** [comment]
Two 1.2 dev versions have been published: 1.2.0-dev.1 (4/6/22) and 1.2.0-dev.2 (4/15/22).  My first thought was to delete thosedev versions, and revert GO:B package.json to "1.1.0".   But unfortunately those dev versions are references in GitHub issues. For example, 1.2.0-dev.2 is mentioned in issue https://github.com/phetsims/geometric-optics-basics/issues/19 that was created by QA.  And I don't know if links to these dev versions have been shared outside of PhET.

If we don't care about version numbers being in-sync, we can do nothing. The result will be:
* GO:B brand=phet-io will be 1.2
* GO:B brands=phet,phet-io will be 1.3
* GO brands=phet,phet-io will be 1.2

If we want the version numbers to stay in-sync, then I recommend:
* publish GO:B with 1.2
* bump GO to 1.3, skipping 1.2
* publish GO and GO:B for PhET-iO with 1.3

@arouinfar @kathy-phet how do you want to proceed?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/769#issuecomment-1295233125, I discovered a huge increase in memory for this (and other ) sims.  Publication is blocked until this increase is investigated and explained.

**Comment by arouinfar** [comment]
> If we want the version numbers to stay in-sync, then I recommend:
>
> * publish GO:B with 1.2
> * bump GO to 1.3, skipping 1.2
> * publish GO and GO:B for PhET-iO with 1.3

Sounds good to me @pixelzoom. Let's proceed with GO:B 1.2 and re-sync the versions for the PhET-iO publication.

**Comment by samreid** [comment]
(At least part of the) memory issue is due to https://github.com/phetsims/chipper/issues/1323

**Comment by samreid** [comment]
I feel it’s unblocked and testing can happen during GO:B dev test.

**Comment by kathy-phet** [comment]
I agree with Sam, let's continue with putting in a GO:B dev test (1.2). And I agree with 1.2 for GO:B, then resync with 1.3 PhET-iO on both Thanks!

**Comment by pixelzoom** [comment]
So the fact that we're not even building things for the advertised "supported platforms" is not block?  OK...  I'll proceed.

**Comment by pixelzoom** [comment]
Dev test submitted on 10/31/2022 🎃 :
* https://github.com/phetsims/qa/issues/847

**Comment by pixelzoom** [comment]
11/10/2022  check-in meeting:

* No one knows what big changes have been made in master since 1.2.0-dev.3 was published.
* #31 (@jonathanolson) and #33 (@jessegreenberg) must be resolved before proceeding, then
* Cross our fingers, create the 1.2 release branch, and proceed with RC testing.

**Comment by pixelzoom** [comment]
11/29/2022:

I updated QA credits for #28, which required publishing 1.2.0-rc.2 before I could publish a production version. So 1.2.0-rc.2 did not go through QA, and I spot-checked the QA credits.

1.2.0 was published.

**Comment by pixelzoom** [comment]
1.2.0 was published on 11/30/2022.
