### ISSUE TITLE
Projection Screen is missing interactive highlight

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics-basics#30]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0

**Browser**
Safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/847, the projection screen is missing an interactive highlight. 

**Steps to reproduce**
1. Turn on interactive highlights
2. On the Lens screen, select the Light scene
3. Hover over or grab the projection screen with your mouse.

**Visuals**

https://user-images.githubusercontent.com/87318828/199779259-f06d818d-8efe-422f-b291-c6ed2b2b62b9.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics: Basics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics-basics/1.2.0-dev.3/phet/geometric-optics-basics_all_phet.html
Version: 1.2.0-dev.3 2022-10-31 21:00:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1813x1056
Pixel Ratio: 1.3333333730697632/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
When interactive highlighting was implemented in common code, @jessegreenberg went around to sims and added `extends InteractiveHighlighting( Node )` were appropriate.  It looks like he missed ProjectionScreenNode.  I've added it in the above commit:

```
export default class ProjectionScreenNode extends InteractiveHighlighting( Node ) {
```

... and it appears to be working now.

@Nancy-Salpepi could you please confirm in master? Feel free to close if it looks OK.

**Comment by Nancy-Salpepi** [comment]
Looks good on master. Closing
