### ISSUE TITLE
Add focal length control to Preferences dialog

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics-basics#32]
Related to https://github.com/phetsims/qa/issues/847

We re-enabled the `focalLengthControl` query parameter in Basics in #15, but it's not currently in the Preferences dialog. 

Allowing users to switch between the indirect/direct focal length modes provides more flexibility to teachers when deciding which flavor of Geometric Optics to use with their students.  We include the focal length control in the Preferences dialog of Geometric Optics, and I think we should do the same in Basics.

@pixelzoom can you add the Focal Length Control to the Preferences dialog?

**Comment by pixelzoom** [comment]
@arouinfar the Focal Length Control was purposely hidden from the Preferences dialog in GO:Basics.

From the requirements that we hashed out in https://github.com/phetsims/geometric-optics-basics/issues/2#issuecomment-1072755619:
> * Default focalLengthControlTypeProperty to 'direct', and remove "Focal Length control" from the Options dialog.

And in the GOPreferencesNode.ts, the control is initially invisible for the basics version, but can be made visible via PhET-iO

```typescript
    const focalLengthModelControl = new FocalLengthModelTypeControl( GOPreferences.focalLengthModelTypeProperty, {
      visible: !options.isBasicsVersion,
      tandem: options.tandem.createTandem( 'focalLengthModelControl' )
    } );
```

So... Do you still want to change this?

**Comment by arouinfar** [comment]
Yes, I want to change this. A lot has happened since the initial design decisions documented in #2. We made decisions in #3 about instrumenting derivative simulations. In #15 we re-enabled `focalLengthControl`. Our approach to query parameters has also shifted within the project. I think `focalLengthControl` is an pedagogically valuable feature and adds flexibility to the simulation. Aside from the default value, there is no reason to treat GO:B differently.

**Comment by pixelzoom** [comment]
Thanks @arouinfar, will do.

**Comment by pixelzoom** [comment]
@arouinfar please review changes to master.  

"Focal Length control" is now present in the Preferences dialog (Simulation tab) for both GO and GO:Basics. The default for GO is "indirect", the default for GO:Basics is "direct".   And both versions support the "focalLengthControl" query parameter (value = "direct"  or "indirect").  

Since we're not on a release branch yet, you can close this issue if it looks OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Looks good in master.
