### ISSUE TITLE
Verify workaround for Safari graphics artifacts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#34]
Originally reported in https://github.com/phetsims/scenery/issues/1503 by @Nancy-Salpepi.

There are graphics artifacts that appear in the new Safari 16.   A workaround was applied, but needs to be verified in RC testing.

**Comment by pixelzoom** [comment]
Ready to review for RC test https://github.com/phetsims/qa/issues/858.

Please close this issue if it verifies OK.

**Comment by Nancy-Salpepi** [comment]
I am really sorry to say this, but I was able to produce an artifact when the light spot was really large. I have to be moving the light very slowly and it quickly disappears making it much harder to notice. @pixelzoom @kathy-phet @jonathanolson I'm really sorry I didn't find it in https://github.com/phetsims/scenery/issues/1503. 
<img width="1049" alt="Screenshot 2022-11-22 at 7 46 37 AM" src="https://user-images.githubusercontent.com/87318828/203325393-adc31d75-0311-458e-9eca-89890b6fe438.png">

**Comment by pixelzoom** [comment]
Bummer.

Back to @jonathanolson for futher investigation.

**Comment by pixelzoom** [comment]
So that we can get this sim published, an option is to publish with this as a known problem, then address it as part of the maintenance release that will be needed for all sims in https://github.com/phetsims/scenery/issues/1503.  @arouinfar @kathy-phet what do you think of that plan?

**Comment by arouinfar** [comment]
@pixelzoom let's move forward with publication and wait for the maintenance release to fix this issue. The artifacts are a bit unsightly, but I don't think they have any serious impact on usability that would warrant delaying publication.

**Comment by kathy-phet** [comment]
@jonathanolson has invested a lot of time to investigating, and at the moment, I do not think further investigation is the best use of his time. The bug is in Safari, and the issues have been submitted. We will give them time to address the issues as there is no reasonable work around on our end, it seems. The issues are transient and do not interfere with the usability of the sim. 

@arouinfar @pixelzoom - Agreed that this is not blocking. I've removed the label. 

Marking this as "on-hold", as we wait for Safari to address this issue.

**Comment by pixelzoom** [comment]
@kathy-phet said:
> Marking this as "on-hold", as we wait for Safari to address this issue.

The issue to mark "on-hold" is the general issue, https://github.com/phetsims/scenery/issues/1503, and I've done so.

Since we don't intend to do anything sim-specific to address this, and will publish this as a known problem, I'm going to close this issue as "won't fix".
