### ISSUE TITLE
White outline around icons

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics-basics#36]
**Test device**
MacBook Pro and Dell
**Operating System**
MacOS 13 and Win 11
**Browser**
Safari and Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/858
On the home screen, the icons are outlined in bright white when the icon is greyed out (not selected). This seems out of the ordinary.

**Visuals**
<img width="714" alt="whiteoutline" src="https://user-images.githubusercontent.com/41024075/203434511-9213616e-a866-4dc1-8d62-c4b87cf75700.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics: Basics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics-basics/1.2.0-rc.1/phet/geometric-optics-basics_all_phet.html
Version: 1.2.0-rc.1 2022-11-18 16:30:43 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
This is true of the published version of Geometric Optics (1.1.1).  It's a leftover from when this sim used to have "projector mode", and I've removed it in master.

I'll defer to @arouinfar on whether to address it in GO:Basics 1.2.  My recommendation is to leave it as-is in the 1.2 branch.

**Comment by arouinfar** [comment]
Good spot @KatieWoe.

>  My recommendation is to leave it as-is in the 1.2 branch.

Agreed @pixelzoom. Glad you fixed it on master, but no need to cherry-pick into 1.2. Closing.
