### ISSUE TITLE
Eliminate space in examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics-basics#39]
For https://github.com/phetsims/qa/issues/939
@arouinfar you accidentally added a space in the middle of "lensScreen" in this tandem id:

<img width="1069" alt="Screenshot 2023-05-11 at 3 01 56 PM" src="https://github.com/phetsims/geometric-optics-basics/assets/87318828/eef5a478-a382-4451-8cd8-44adec8c5dad">

**Comment by arouinfar** [comment]
Space removed in the above commit, closing.
