### ISSUE TITLE
Studio tree for geometric-optics-basics is empty except for `phetioEngine`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#4]
While attempting to test https://github.com/phetsims/geometric-optics-basics/issues/3, @arouinfar ran  into problems. That began a series of comments that are not related to that issue.  So I'm moving those comments here.

---

@arouinfar said:
> @pixelzoom did you forget to push to master? I've pulled all and cleared the cache, but the Studio tree for geometric-optics-basics is empty except for `phetioEngine`.

@samreid said:
> This may be due to a phet-io problem.  I'm seeing that the `simStarted` event is not processing properly, so there is an error in the console.  Probably not a geometric-optics-specific problem.  Tagging @zepumph in case he has ideas.
> 
> Specifically, the `simStarted` event is going nowhere because `phet.phetio.dataStream` is coming up falsy in the guard.

@arouinfar said:
> Thanks @samreid looks like it is indeed a general problem. I tried a few other sims and they're all showing the same empty tree.

@samreid said:
> Thanks, I moved it to a side issue. (EDIT: see https://github.com/phetsims/phet-io/issues/1845)

@samreid said:
> OK I pushed a fix in the issue. @arouinfar can you please pull and test?

**Comment by zepumph** [comment]
Since https://github.com/phetsims/phet-io/issues/1845 is closed, most like this can be also.

**Comment by arouinfar** [comment]
The tree is no longer empty in master, closing.
