### ISSUE TITLE
Allow the flat mirror to be dragged freely.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#5]
For the Basics version... An additional change we could make in the Mirror screen is to allow free dragging of all objects (including framed objects), and add the drag-locked toggle button. But I'm reluctant to do that until PhET-iO decisions have been made in https://github.com/phetsims/geometric-optics-basics/issues/3.

In https://github.com/phetsims/geometric-optics-basics/issues/2#issuecomment-1048443377, @arouinfar said:
>  I agree that it would be a big improvement to allow free-dragging of the object on the Mirror screen, but it makes sense to defer until https://github.com/phetsims/geometric-optics-basics/issues/3 is settled.

**Comment by pixelzoom** [comment]
For Basics, all objects are now freely draggable in both Lens & Mirror screens, and both screens have the drag-locked toggle button.  

@arouinfar please review, close if it looks OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, this looks great in master.
