### ISSUE TITLE
Change initial position of framed object in Mirror screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#6]
Since framed objects can be freely dragged in the Mirror screen, move initial position to something like this, where the object is vertically centered on the optical axis.  The same position used in the Lens screen will probably work.

![screenshot_334](https://user-images.githubusercontent.com/3046552/155629365-6d55465d-b40c-4d08-bae5-28509370ae1a.png)

**Comment by pixelzoom** [comment]
Done in the above commit. Initial position of framed object is ( -170, 27 ) for both screens in the Basics version.  @arouinfar please review, close if this looks OK.

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom!
