### ISSUE TITLE
Feature-complete test drive.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#7]
_Geometric Optics: Basics_ is now feature-complete, and the design team is encourage to test drive it with high priority.  Please create new GitHub issues for any problems or change requests.   Unassign yourself when you have completed your test drive.

If there's anyone else who should be looking at the sim, please assign this issue to them.

**Comment by pixelzoom** [comment]
If there's anyone else who should be looking at the sim, please assign this issue to them.

**Comment by ariel-phet** [comment]
Test drive complete, looking great!

**Comment by pixelzoom** [comment]
Thanks @ariel-phet.

**Comment by pixelzoom** [comment]
I'm assuming this is done, so closing.
