### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#8]
[model.md](https://github.com/phetsims/geometric-optics-basics/edit/master/doc/model.md) should be pretty sparse, and refer to geometric-optic model.md.  For example, see [phet-scale-basics ](https://github.com/phetsims/ph-scale-basics/blob/master/doc/model.md).

**Comment by pixelzoom** [comment]
This is done. But I'm not going to assign for review until geometric-optics model.md has been completed.

**Comment by pixelzoom** [comment]
@arouinfar ready for review. This should be an easy one, because it basically points over to geometric-optics, and notes a couple of differences.  If you'd like to modify, feel free to do so directly.

This must be reviewed before code review can begin.

**Comment by arouinfar** [comment]
@pixelzoom sorry I missed this when reviewing model.md for the main sim. It makes sense to keep the bulk of the content in geometric-optics and note the major differences, which you've done. Closing.
