### ISSUE TITLE
implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#9]
[implementation-notes.md](https://github.com/phetsims/geometric-optics-basics/blob/master/doc/implementation-notes.md) should be pretty sparse, and refer to geometric-optic implementation-notes.md.

**Comment by pixelzoom** [comment]
This is done. But I'm not going to assign for review until geometric-optics implementation-notes.md has been completed.

**Comment by pixelzoom** [comment]
[implementation-notes.md](https://github.com/phetsims/geometric-optics-basics/blob/master/doc/implementation-notes.md) is ready for review by whoever doese the sim code review.

**Comment by pixelzoom** [comment]
@jonathanolson Please review as part of code review https://github.com/phetsims/geometric-optics/issues/402.

**Comment by jonathanolson** [comment]
These look great, the way the differences are described is very helpful.
